### ISSUE TITLE
[BUILD] MacOS build needs small updates

### ISSUE THREAD

**Issue by jeroz1** [RavenProject/Ravencoin#1006]
This is how I got develop it to build on Big Sur (11.2.3):

```
git clone https://github.com/RavenProject/Ravencoin.git
cd Ravencoin/
git checkout develop

brew install automake berkeley-db4 libtool boost miniupnpc openssl pkg-config protobuf python qt5 libevent qrencode
echo 'export PATH="/usr/local/opt/berkeley-db@4/bin:$PATH"' >> ~/.bash_profile
echo 'export PATH="/usr/local/opt/icu4c/bin:$PATH"' >> ~/.bash_profile
echo 'export PATH="/usr/local/opt/icu4c/sbin:$PATH"' >> ~/.bash_profile
echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile
echo 'export PATH="/usr/local/opt/qt@5/bin:$PATH"' >> ~/.bash_profile
source ~/.bash_profile
brew install librsvg #Optional For dmg package
brew link berkeley-db4 --force

./autogen.sh
./configure
make -j4
make check # Optional
make deploy # Optional
```
Main differences:
- `qt` -> `qt5`
- brew asks user to add paths to the profile
- berkeley-db4 needs to be forced.

**Comment by lorancecall** [comment]
The error message I've got after followed issue instruction on #1006 

'''
wallet/wallet.cpp:2754:5: error: use of undeclared identifier '**random_shuffle**'
    random_shuffle(vCoins.begin(), vCoins.end(), GetRandInt);
    ^
wallet/wallet.cpp:2957:5: error: use of undeclared identifier '**random_shuffle**'
    random_shuffle(vCoins.begin(), vCoins.end(), GetRandInt);
    ^
wallet/wallet.cpp:2958:36: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
    #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
                                   ^
wallet/wallet.cpp:3048:40: warning: unknown warning group '-Wmaybe-uninitialized', ignored [-Wunknown-warning-option]
        #pragma GCC diagnostic ignored "-Wmaybe-uninitialized"
                                       ^
wallet/wallet.cpp:4035:57: warning: loop variable 'item' of type 'const std::pair<std::string, std::string> &' (aka 'const pair<basic_string<char>, basic_string<char>> &') binds to a temporary constructed from type 'std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<std::__1::basic_string<char>, std::__1::basic_string<char>>, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, std::__1::basic_string<char>>, void *> *, long>>::reference' (aka 'pair<const std::__1::basic_string<char>, std::__1::basic_string<char>> &') [-Wrange-loop-construct]
        for (const std::pair<std::string, std::string> &item : mapAddressBook[address].destdata)
                                                        ^
wallet/wallet.cpp:4035:14: note: use non-reference type 'std::pair<std::string, std::string>' (aka 'pair<basic_string<char>, basic_string<char>>') to make construction explicit or type 'const std::__1::__map_iterator<std::__1::__tree_iterator<std::__1::__value_type<std::__1::basic_string<char>, std::__1::basic_string<char>>, std::__1::__tree_node<std::__1::__value_type<std::__1::basic_string<char>, std::__1::basic_string<char>>, void *> *, long>>::value_type &' (aka 'const pair<const std::__1::basic_string<char>, std::__1::basic_string<char>> &') to prevent copying
        for (const std::pair<std::string, std::string> &item : mapAddressBook[address].destdata)
             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
wallet/wallet.cpp:4420:61: warning: loop variable 'item' of type 'const std::pair<CTxDestination, CAddressBookData> &' (aka 'const pair<variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData> &') binds to a temporary constructed from type 'std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::__value_type<boost::variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData>, std::__1::__tree_node<std::__1::__value_type<boost::variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData>, void *> *, long>>::reference' (aka 'const pair<const boost::variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData> &') [-Wrange-loop-construct]
    for (const std::pair<CTxDestination, CAddressBookData>& item : mapAddressBook)
                                                            ^
wallet/wallet.cpp:4420:10: note: use non-reference type 'std::pair<CTxDestination, CAddressBookData>' (aka 'pair<variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData>') to make construction explicit or type 'const std::__1::__map_const_iterator<std::__1::__tree_const_iterator<std::__1::__value_type<boost::variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData>, std::__1::__tree_node<std::__1::__value_type<boost::variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData>, void *> *, long>>::value_type &' (aka 'const pair<const boost::variant<CNoDestination, CKeyID, CScriptID>, CAddressBookData> &') to prevent copying
    for (const std::pair<CTxDestination, CAddressBookData>& item : mapAddressBook)
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
4 warnings and 2 errors generated.
make[2]: *** [wallet/libraven_wallet_a-wallet.o] Error 1
make[2]: *** Waiting for unfinished jobs....
10 warnings generated.
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
'''

**Comment by lorancecall** [comment]
Tested #1041, update the code manually and build from scratch according to the @jeroz1 instruction above.
Result showed error related to the Qt as shown below.

```debug
  CXX      qt/test/test_raven_qt-test_main.o
In file included from qt/test/rpcnestedtests.cpp:6:
In file included from qt/test/rpcnestedtests.h:10:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/QTest:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/qtest.h:221:19: warning: 'canConvert' is deprecated [-Wdeprecated-declarations]
            if (v.canConvert(QMetaType::QString)) {
                  ^
/usr/local/include/QtCore/qvariant.h:259:5: note: 'canConvert' has been explicitly marked deprecated here
    QT_DEPRECATED_VERSION_6_0
    ^
/usr/local/include/QtCore/qglobal.h:363:44: note: expanded from macro 'QT_DEPRECATED_VERSION_6_0'
# define QT_DEPRECATED_VERSION_6_0         QT_DEPRECATED
                                           ^
/usr/local/include/QtCore/qglobal.h:272:25: note: expanded from macro 'QT_DEPRECATED'
#  define QT_DEPRECATED Q_DECL_DEPRECATED
                        ^
/usr/local/include/QtCore/qcompilerdetection.h:1152:31: note: expanded from macro 'Q_DECL_DEPRECATED'
#  define Q_DECL_DEPRECATED [[deprecated]]
                              ^
In file included from qt/test/rpcnestedtests.cpp:6:
In file included from qt/test/rpcnestedtests.h:10:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/QTest:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/qtest.h:243:14: error: redefinition of 'toString'
inline char *toString(const std::pair<T1, T2> &pair)
             ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/qtest.h:235:14: note: previous definition is here
inline char *toString(const QPair<T1, T2> &pair)
             ^
In file included from qt/test/test_main.cpp:11:
In file included from qt/test/rpcnestedtests.h:10:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/QTest:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/qtest.h:221:19: warning: 'canConvert' is deprecated [-Wdeprecated-declarations]
            if (v.canConvert(QMetaType::QString)) {
                  ^
/usr/local/include/QtCore/qvariant.h:259:5: note: 'canConvert' has been explicitly marked deprecated here
    QT_DEPRECATED_VERSION_6_0
    ^
/usr/local/include/QtCore/qglobal.h:363:44: note: expanded from macro 'QT_DEPRECATED_VERSION_6_0'
# define QT_DEPRECATED_VERSION_6_0         QT_DEPRECATED
                                           ^
/usr/local/include/QtCore/qglobal.h:272:25: note: expanded from macro 'QT_DEPRECATED'
#  define QT_DEPRECATED Q_DECL_DEPRECATED
                        ^
/usr/local/include/QtCore/qcompilerdetection.h:1152:31: note: expanded from macro 'Q_DECL_DEPRECATED'
#  define Q_DECL_DEPRECATED [[deprecated]]
                              ^
In file included from qt/test/test_main.cpp:11:
In file included from qt/test/rpcnestedtests.h:10:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/QTest:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/qtest.h:243:14: error: redefinition of 'toString'
inline char *toString(const std::pair<T1, T2> &pair)
             ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtTest.framework/Headers/qtest.h:235:14: note: previous definition is here
inline char *toString(const QPair<T1, T2> &pair)
             ^
In file included from qt/test/compattests.cpp:6:
In file included from ./qt/paymentrequestplus.h:18:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/QByteArray:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:126:21: error: reference to non-static member function must be called
        Q_ASSERT(ba.ref.isStatic());
                 ~~~^~~
/usr/local/include/QtCore/qglobal.h:905:30: note: expanded from macro 'Q_ASSERT'
#    define Q_ASSERT(cond) ((cond) ? static_cast<void>(0) : qt_assert(#cond, __FILE__, __LINE__))
                             ^~~~
In file included from qt/test/compattests.cpp:6:
In file included from ./qt/paymentrequestplus.h:18:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/QByteArray:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:469:14: error: unknown type name 'QNoImplicitBoolCast'
    operator QNoImplicitBoolCast() const;
             ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:471:40: error: no type named 'AllocationOptions' in 'QTypedArrayData<char>'; did you mean 'AllocationOption'?
    void reallocData(uint alloc, Data::AllocationOptions options);
                                 ~~~~~~^~~~~~~~~~~~~~~~~
                                       AllocationOption
/usr/local/include/QtCore/qarraydata.h:54:10: note: 'AllocationOption' declared here
    enum AllocationOption {
         ^
In file included from qt/test/compattests.cpp:6:
In file included from ./qt/paymentrequestplus.h:18:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/QByteArray:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:189:84: error: no member named 'sharedNull' in 'QTypedArrayData<char>'
    inline QByteArray(QByteArray && other) noexcept : d(other.d) { other.d = Data::sharedNull(); }
                                                                             ~~~~~~^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:459:42: error: no member named 'size' in 'QTypedArrayData<char>'
    inline int count() const { return d->size; }
                                      ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:460:36: error: no member named 'size' in 'QTypedArrayData<char>'
    int length() const { return d->size; }
                                ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:494:52: error: no member named 'sharedNull' in 'QTypedArrayData<char>'
inline QByteArray::QByteArray() noexcept : d(Data::sharedNull()) { }
                                             ~~~~~~^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:495:44: error: reference to non-static member function must be called; did you mean to call it with no arguments?
inline QByteArray::~QByteArray() { if (!d->ref.deref()) Data::deallocate(d); }
                                        ~~~^~~
                                              ()
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:495:47: error: member reference base type 'bool' is not a structure or union
inline QByteArray::~QByteArray() { if (!d->ref.deref()) Data::deallocate(d); }
                                        ~~~~~~^~~~~~
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:497:13: error: no member named 'size' in 'QTypedArrayData<char>'
{ return d->size; }
         ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:500:47: error: no member named 'data' in 'QTypedArrayData<char>'
{ Q_ASSERT(uint(i) < uint(size())); return d->data()[i]; }
                                           ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:502:47: error: no member named 'data' in 'QTypedArrayData<char>'
{ Q_ASSERT(uint(i) < uint(size())); return d->data()[i]; }
                                           ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:504:41: error: no member named 'data' in 'QTypedArrayData<char>'
{ Q_ASSERT(i < uint(size())); return d->data()[i]; }
                                     ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:507:13: error: no member named 'size' in 'QTypedArrayData<char>'
{ return d->size == 0; }
         ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:510:13: error: no member named 'data' in 'QTypedArrayData<char>'
{ return d->data(); }
         ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:512:13: error: no member named 'data' in 'QTypedArrayData<char>'
{ return d->data(); }
         ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:515:23: error: no member named 'data' in 'QTypedArrayData<char>'
{ detach(); return d->data(); }
                   ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:517:13: error: no member named 'data' in 'QTypedArrayData<char>'
{ return d->data(); }
         ~  ^
/usr/local/Cellar/qt@5/5.15.2/lib/QtCore.framework/Headers/qbytearray.h:519:13: error: no member named 'data' in 'QTypedArrayData<char>'
{ return d->data(); }
         ~  ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
make[2]: *** [qt/test/test_raven_qt-compattests.o] Error 1
make[2]: *** Waiting for unfinished jobs....
In file included from qt/test/rpcnestedtests.cpp:14:
In file included from ./qt/rpcconsole.h:9:
In file included from ./qt/guiutil.h:13:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/QHeaderView:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/qheaderview.h:249:10: warning: 'QHeaderView::initStyleOption' hides overloaded virtual function [-Woverloaded-virtual]
    void initStyleOption(QStyleOptionHeader *option) const;
         ^
/usr/local/include/QtWidgets/qframe.h:119:18: note: hidden overloaded virtual function 'QFrame::initStyleOption' declared here: type mismatch at 1st parameter ('QStyleOptionFrame *' vs 'QStyleOptionHeader *')
    virtual void initStyleOption(QStyleOptionFrame *option) const;
                 ^
In file included from qt/test/rpcnestedtests.cpp:14:
In file included from ./qt/rpcconsole.h:9:
In file included from ./qt/guiutil.h:18:
In file included from /usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/QTableView:1:
/usr/local/Cellar/qt@5/5.15.2/lib/QtWidgets.framework/Headers/qtableview.h:152:46: error: only virtual member functions can be marked 'override'
    QStyleOptionViewItem viewOptions() const override;
                                             ^~~~~~~~
1 warning and 1 error generated.
make[2]: *** [qt/test/test_raven_qt-test_main.o] Error 1
2 warnings and 2 errors generated.
make[2]: *** [qt/test/test_raven_qt-rpcnestedtests.o] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all-recursive] Error 1
```

**Comment by lorancecall** [comment]
After applied the change posted on #1041, I success on building.

Some issue can happen if both qt (ver 6) and qt@5 are installed together. After removing both and re-installing qt@5 resolve this issue. If follow the @jeroz1 instruction above, it will probably not happen unless someone uses qt v6 for their regular dev works.

**Comment by lorancecall** [comment]
This will be not an issue but `install_cli.sh` is not executable after build

<img width="491" alt="Screen Shot 2021-06-01 at 11 47 50 AM" src="https://user-images.githubusercontent.com/84116812/120352930-45ccca80-c2cf-11eb-90a2-ebf5042faba0.png">

need to grant permission to be executable `chmod +x install_cli.sh` during build process
