### PR TITLE
Qt compilation error fix

### PR DESCRIPTION
**Pull request by bedri**
Fixes compilation errors: Added inclusion of QPainterPath header file to src/qt/overviewpage.cpp, src/qt/trafficgraphwidget.cpp and src/qt/trafficgraphwidget.h

Today, at another PIVX based project that I worked on I got errors in trafficgraphwidget files. When I pull and compile Ravencoin develop branch I got the the same following compilation errors as well.
```
qt/trafficgraphwidget.cpp: In member function ‘void TrafficGraphWidget::paintPath(QPainterPath&, QQueue<float>&)’:
qt/trafficgraphwidget.cpp:55:9: error: invalid use of incomplete type ‘class QPainterPath’
   55 |         path.moveTo(x, YMARGIN + h);
      |         ^~~~
```
```
qt/trafficgraphwidget.cpp: In member function ‘virtual void TrafficGraphWidget::paintEvent(QPaintEvent*)’:
qt/trafficgraphwidget.cpp:108:22: error: aggregate ‘QPainterPath p’ has incomplete type and cannot be defined
  108 |         QPainterPath p;
      |                      ^
```
```
qt/overviewpage.cpp: In member function ‘virtual void AssetViewDelegate::paint(QPainter*, const QStyleOptionViewItem&, const QModelIndex&) const’:
qt/overviewpage.cpp:216:22: error: aggregate ‘QPainterPath path’ has incomplete type and cannot be defined
  216 |         QPainterPath path;
      |                      ^~~~
```

The problem is that QPainterPath class is being used as type identifier but QPainterPath header file is not included in the files.
I am running OpenSuSE Tumbleweed OS and keeping all libraries up to date. The current QT version on my system is 5.15.0
It seems QT has made some basic changes in one of their latest updates.

I personally didn't have chance to check this inclusion of QPainterPath header file creates problem with the QT version of 5.9.x but my colleagues had checked and they get no errors after the inclusion of this header file.

There are also new warnings appearing and I will create an issue about them but since the errors given above blocks the compilation, I wanted to create this pull request quickly for a fix.

Thank you in advance.

### CODE REVIEW

**Comment by ririen** [comment]
Hmm, I wrote 1 pull request which corrects these errors and compilation worked fine. Now I have two pull requests with the same bug so let developers decide which one to push and which to close.

Fix build with Qt 5.15+ https://github.com/RavenProject/Ravencoin/pull/783

**Comment by bedri** [comment]
@ririen I did not see yours when I open the pull request. Sorry.
There is although one more file that should be fixed that you did not include (qt/overviewpage.cpp). If you wish, include that file as well and I can close this pull request if you wish.
